project:
  type: website

website:
  title: "My Quarto Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Blog
        menu:
          - href: post/post1.qmd
            text: First Blog Post

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
